# Generated by Django 5.2.5 on 2025-08-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0002_alter_employee_department_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="employees.employee",
            ),
        ),
        migrations.DeleteModel(
            name="Performance",
        ),
    ]
